image: node:12.16.1

cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  script:
    - npm install -g @angular/cli@9.1.7
    - npm install
    - ng build --prod --base-href '/ngrome2019/'
    - npm run scully
    - mv dist/static/* public/

  artifacts:
    paths:
      - public
  only:
    - develop
deploy_production:
  stage: deploy
  only:
    - master
  script:
    - npm install -g @angular/cli@9.1.7
    - npm install -g firebase-tools
    - npm install
    - npm run build
    - npm run scully
    - firebase use --token $FIREBASE_DEPLOY_KEY production
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
